services:
  http-api:
    build: ../cont/http-api
    environment:
      HOST_GID: ${HOST_UID}
      HOST_UID: ${HOST_UID}
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_ORG: ${PROJECT_ORG}
      PROJECT_DESCRIPTION: ${PROJECT_DESCRIPTION}
      PROJECT_AUTHORS: ${PROJECT_AUTHORS}
      HTTP_PORT: ${HTTP_PORT}
      HEALTCHECK_HTTP_PATH: ${HEALTCHECK_HTTP_PATH}
      TZ: ${TIME_ZONE}
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
    expose: 
    - ${HTTP_PORT}
    ports: 
    - ${HTTP_PORT}:${HTTP_PORT}
    volumes:
    - ../../../../dev:/var/www